# base_strategy.py
"""
Base strategy interface for trading strategies.

All trading strategies must implement this interface.
The backtest engine and live_trader accept any BaseStrategy.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional
import pandas as pd


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Attributes:
        symbol: Trading symbol
        action: "BUY", "SELL", or "HOLD"
        confidence: Signal confidence from 0.0 to 1.0
        entry_price: Suggested entry price
        stop_loss: Stop loss price level
        take_profit: Take profit price level
        reason: Human-readable explanation for the signal
        volatility_pct: ATR-based volatility percentage (for risk check)
    """
    symbol: str
    action: str          # "BUY", "SELL", or "HOLD"
    confidence: float    # 0.0 to 1.0
    entry_price: float
    stop_loss: float
    take_profit: float
    reason: str          # Human-readable explanation
    volatility_pct: Optional[float] = None  # ATR-based volatility %


class BaseStrategy(ABC):
    """
    All trading strategies must implement this interface.
    The backtest engine and live_trader accept any BaseStrategy.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Strategy name for logging and identification."""
        ...

    @abstractmethod
    def generate_signals(
        self,
        symbol: str,
        df: pd.DataFrame,
        df_15m: Optional[pd.DataFrame] = None,
    ) -> list[Signal]:
        """
        Given an OHLCV DataFrame, return a list of Signals.

        Args:
            symbol: Trading symbol
            df: Primary OHLCV DataFrame with columns [open, high, low, close, volume]
                Index should be DatetimeIndex in IST timezone
            df_15m: Optional higher-timeframe OHLCV for trend alignment.
                Strategies that use it must fail-open (treat as pass) when
                it is None or too short.

        Returns:
            List of Signal objects. Returns empty list if no action should be taken.
        """
        ...

    @abstractmethod
    def required_bars(self) -> int:
        """
        Minimum number of historical bars needed to generate signals.
        
        Returns:
            Integer representing minimum required bars
        """
        ...

    def validate_dataframe(self, df: pd.DataFrame) -> bool:
        """
        Validate that DataFrame has required columns and structure.
        
        Args:
            df: DataFrame to validate
            
        Returns:
            True if valid, False otherwise
        """
        required_columns = ['open', 'high', 'low', 'close', 'volume']
        
        if not isinstance(df, pd.DataFrame):
            return False
            
        if len(df) == 0:
            return False
            
        missing_cols = set(required_columns) - set(df.columns)
        if missing_cols:
            return False
            
        return True
