# universe.py
"""
AUTO-GENERATED - do not edit by hand.

NIFTY 500 universe (official NSE constituent list, EQ series)
intersected with instruments available on Groww (NSE/CASH).
Sectors come from NSE's Industry column; curated entries in
sectors.py always override the generated mapping.

Source: https://nsearchives.nseindia.com/content/indices/ind_nifty500list.csv
Fetched: 2026-09-18
Regenerate: python tools/update_universe.py
"""

FETCHED = "2026-09-18"

NIFTY500 = [
    "360ONE",
    "3MINDIA",
    "AADHARHFC",
    "AARTIIND",
    "AAVAS",
    "ABB",
    "ABBOTINDIA",
    "ABCAPITAL",
    "ABDL",
    "ABFRL",
    "ABLBL",
    "ABREL",
    "ABSLAMC",
    "ACC",
    "ACE",
    "ACMESOLAR",
    "ACUTAAS",
    "ADANIENSOL",
    "ADANIENT",
    "ADANIGREEN",
    "ADANIPORTS",
    "ADANIPOWER",
    "AEGISLOG",
    "AEGISVOPAK",
    "AFCONS",
    "AFFLE",
    "AIAENG",
    "AIIL",
    "AJANTPHARM",
    "ALKEM",
    "AMBER",
    "AMBUJACEM",
    "ANANDRATHI",
    "ANANTRAJ",
    "ANGELONE",
    "ANTHEM",
    "ANURAS",
    "APARINDS",
    "APLAPOLLO",
    "APOLLOHOSP",
    "APOLLOTYRE",
    "APTUS",
    "ARE&M",
    "ASAHIINDIA",
    "ASHOKLEY",
    "ASIANPAINT",
    "ASTERDM",
    "ASTRAL",
    "ATGL",
    "ATHERENERG",
    "ATUL",
    "AUBANK",
    "AUROPHARMA",
    "AWL",
    "AXISBANK",
    "BAJAJ-AUTO",
    "BAJAJFINSV",
    "BAJAJHFL",
    "BAJAJHLDNG",
    "BAJFINANCE",
    "BALKRISIND",
    "BALRAMCHIN",
    "BANDHANBNK",
    "BANKBARODA",
    "BANKINDIA",
    "BATAINDIA",
    "BAYERCROP",
    "BBTC",
    "BDL",
    "BEL",
    "BELRISE",
    "BEML",
    "BERGEPAINT",
    "BHARATFORG",
    "BHARTIARTL",
    "BHARTIHEXA",
    "BHEL",
    "BIKAJI",
    "BIOCON",
    "BLS",
    "BLUEDART",
    "BLUEJET",
    "BLUESTARCO",
    "BOSCHLTD",
    "BPCL",
    "BRIGADE",
    "BRITANNIA",
    "BSE",
    "BSOFT",
    "CAMS",
    "CANBK",
    "CANFINHOME",
    "CANHLIFE",
    "CAPLIPOINT",
    "CARBORUNIV",
    "CARTRADE",
    "CASTROLIND",
    "CCL",
    "CDSL",
    "CEATLTD",
    "CEMPRO",
    "CENTRALBK",
    "CESC",
    "CGCL",
    "CGPOWER",
    "CHALET",
    "CHAMBLFERT",
    "CHENNPETRO",
    "CHOICEIN",
    "CHOLAFIN",
    "CHOLAHLDNG",
    "CIEINDIA",
    "CIPLA",
    "CLEAN",
    "COALINDIA",
    "COCHINSHIP",
    "COFORGE",
    "COHANCE",
    "COLPAL",
    "CONCOR",
    "CONCORDBIO",
    "COROMANDEL",
    "CPPLUS",
    "CRAFTSMAN",
    "CREDITACC",
    "CRISIL",
    "CROMPTON",
    "CUB",
    "CUMMINSIND",
    "CYIENT",
    "DABUR",
    "DALBHARAT",
    "DATAPATTNS",
    "DCMSHRIRAM",
    "DEEPAKFERT",
    "DEEPAKNTR",
    "DELHIVERY",
    "DEVYANI",
    "DIVISLAB",
    "DIXON",
    "DLF",
    "DMART",
    "DOMS",
    "DRREDDY",
    "ECLERX",
    "EICHERMOT",
    "EIDPARRY",
    "EIHOTEL",
    "ELECON",
    "ELGIEQUIP",
    "EMAMILTD",
    "EMCURE",
    "EMMVEE",
    "ENDURANCE",
    "ENGINERSIN",
    "ENRIN",
    "ERIS",
    "ESCORTS",
    "ETERNAL",
    "EXIDEIND",
    "FACT",
    "FEDERALBNK",
    "FINCABLES",
    "FIRSTCRY",
    "FIVESTAR",
    "FLUOROCHEM",
    "FORCEMOT",
    "FORTIS",
    "FSL",
    "GABRIEL",
    "GAIL",
    "GALLANTT",
    "GESHIP",
    "GICRE",
    "GILLETTE",
    "GLAND",
    "GLAXO",
    "GLENMARK",
    "GMDCLTD",
    "GMRAIRPORT",
    "GODFRYPHLP",
    "GODIGIT",
    "GODREJCP",
    "GODREJIND",
    "GODREJPROP",
    "GPIL",
    "GRANULES",
    "GRAPHITE",
    "GRASIM",
    "GRAVITA",
    "GROWW",
    "GRSE",
    "GVT&D",
    "HAL",
    "HAVELLS",
    "HBLENGINE",
    "HCLTECH",
    "HDBFS",
    "HDFCAMC",
    "HDFCBANK",
    "HDFCLIFE",
    "HEROMOTOCO",
    "HEXT",
    "HINDALCO",
    "HINDCOPPER",
    "HINDPETRO",
    "HINDUNILVR",
    "HINDZINC",
    "HOMEFIRST",
    "HONASA",
    "HONAUT",
    "HSCL",
    "HUDCO",
    "HYUNDAI",
    "ICICIAMC",
    "ICICIBANK",
    "ICICIGI",
    "ICICIPRULI",
    "IDBI",
    "IDEA",
    "IDFCFIRSTB",
    "IEX",
    "IFCI",
    "IGIL",
    "IGL",
    "IIFL",
    "IKS",
    "INDGN",
    "INDHOTEL",
    "INDIACEM",
    "INDIAMART",
    "INDIANB",
    "INDIGO",
    "INDUSINDBK",
    "INDUSTOWER",
    "INFY",
    "INOXWIND",
    "INTELLECT",
    "IOB",
    "IOC",
    "IPCALAB",
    "IRB",
    "IRCON",
    "IRCTC",
    "IREDA",
    "IRFC",
    "ITC",
    "ITCHOTELS",
    "ITI",
    "J&KBANK",
    "JAINREC",
    "JBMA",
    "JINDALSAW",
    "JINDALSTEL",
    "JIOFIN",
    "JKCEMENT",
    "JKTYRE",
    "JMFINANCIL",
    "JPPOWER",
    "JSL",
    "JSWCEMENT",
    "JSWDULUX",
    "JSWENERGY",
    "JSWINFRA",
    "JSWSTEEL",
    "JUBLFOOD",
    "JUBLINGREA",
    "JUBLPHARMA",
    "JWL",
    "JYOTICNC",
    "KAJARIACER",
    "KALYANKJIL",
    "KARURVYSYA",
    "KAYNES",
    "KEC",
    "KEI",
    "KFINTECH",
    "KIMS",
    "KIRLOSENG",
    "KOTAKBANK",
    "KPIL",
    "KPITTECH",
    "KPRMILL",
    "LALPATHLAB",
    "LATENTVIEW",
    "LAURUSLABS",
    "LEMONTREE",
    "LENSKART",
    "LGEINDIA",
    "LICHSGFIN",
    "LICI",
    "LINDEINDIA",
    "LLOYDSME",
    "LODHA",
    "LT",
    "LTF",
    "LTFOODS",
    "LTM",
    "LTTS",
    "LUPIN",
    "M&M",
    "M&MFIN",
    "MAHABANK",
    "MANAPPURAM",
    "MANKIND",
    "MAPMYINDIA",
    "MARICO",
    "MARUTI",
    "MAXHEALTH",
    "MAZDOCK",
    "MCX",
    "MEDANTA",
    "MEESHO",
    "MFSL",
    "MGL",
    "MINDACORP",
    "MMTC",
    "MOTHERSON",
    "MOTILALOFS",
    "MPHASIS",
    "MRF",
    "MRPL",
    "MSUMI",
    "MUTHOOTFIN",
    "NAM-INDIA",
    "NATCOPHARM",
    "NATIONALUM",
    "NAUKRI",
    "NAVA",
    "NAVINFLUOR",
    "NBCC",
    "NCC",
    "NESTLEIND",
    "NETWEB",
    "NEULANDLAB",
    "NEWGEN",
    "NH",
    "NHPC",
    "NIACL",
    "NIVABUPA",
    "NLCINDIA",
    "NMDC",
    "NSLNISP",
    "NTPC",
    "NTPCGREEN",
    "NUVAMA",
    "NUVOCO",
    "NYKAA",
    "OBEROIRLTY",
    "OFSS",
    "OIL",
    "OLAELEC",
    "OLECTRA",
    "ONESOURCE",
    "ONGC",
    "PAGEIND",
    "PARADEEP",
    "PATANJALI",
    "PAYTM",
    "PCBL",
    "PERSISTENT",
    "PETRONET",
    "PFC",
    "PFIZER",
    "PFOCUS",
    "PGEL",
    "PHOENIXLTD",
    "PIDILITIND",
    "PIIND",
    "PINELABS",
    "PIRAMALFIN",
    "PNB",
    "PNBHOUSING",
    "POLICYBZR",
    "POLYCAB",
    "POLYMED",
    "POONAWALLA",
    "POWERGRID",
    "POWERINDIA",
    "PPLPHARMA",
    "PREMIERENE",
    "PRESTIGE",
    "PTCIL",
    "PVRINOX",
    "PWL",
    "RADICO",
    "RAILTEL",
    "RAINBOW",
    "RAMCOCEM",
    "RBLBANK",
    "RECLTD",
    "REDINGTON",
    "RELIANCE",
    "RHIM",
    "RITES",
    "RKFORGE",
    "RPOWER",
    "RRKABEL",
    "RVNL",
    "SAGILITY",
    "SAIL",
    "SAILIFE",
    "SAMMAANCAP",
    "SAPPHIRE",
    "SARDAEN",
    "SAREGAMA",
    "SBFC",
    "SBICARD",
    "SBILIFE",
    "SBIN",
    "SCHAEFFLER",
    "SCHNEIDER",
    "SCI",
    "SHREECEM",
    "SHRIRAMFIN",
    "SHYAMMETL",
    "SIEMENS",
    "SIGNATURE",
    "SJVN",
    "SOBHA",
    "SOLARINDS",
    "SONACOMS",
    "SONATSOFTW",
    "SPLPETRO",
    "SRF",
    "STARHEALTH",
    "SUMICHEM",
    "SUNDARMFIN",
    "SUNPHARMA",
    "SUNTV",
    "SUPREMEIND",
    "SUZLON",
    "SWANCORP",
    "SWIGGY",
    "SYNGENE",
    "SYRMA",
    "TARIL",
    "TATACAP",
    "TATACHEM",
    "TATACOMM",
    "TATACONSUM",
    "TATAELXSI",
    "TATAINVEST",
    "TATAPOWER",
    "TATASTEEL",
    "TATATECH",
    "TBOTEK",
    "TCS",
    "TECHM",
    "TECHNOE",
    "TEGA",
    "TEJASNET",
    "TENNIND",
    "THELEELA",
    "THERMAX",
    "TIINDIA",
    "TIMKEN",
    "TITAGARH",
    "TITAN",
    "TMCV",
    "TMPV",
    "TORNTPHARM",
    "TORNTPOWER",
    "TRAVELFOOD",
    "TRENT",
    "TRIDENT",
    "TRITURBINE",
    "TTML",
    "TVSMOTOR",
    "UBL",
    "UCOBANK",
    "ULTRACEMCO",
    "UNIONBANK",
    "UNITDSPR",
    "UNOMINDA",
    "UPL",
    "URBANCO",
    "USHAMART",
    "UTIAMC",
    "VBL",
    "VEDL",
    "VIJAYA",
    "VMM",
    "VOLTAS",
    "VTL",
    "WAAREEENER",
    "WELCORP",
    "WELSPUNLIV",
    "WHIRLPOOL",
    "WIPRO",
    "WOCKPHARMA",
    "YESBANK",
    "ZEEL",
    "ZENSARTECH",
    "ZENTEC",
    "ZFCVINDIA",
    "ZYDUSLIFE",
    "ZYDUSWELL",
]

SECTORS = {
    "360ONE": "FINANCE",
    "3MINDIA": "OTHER",
    "AADHARHFC": "FINANCE",
    "AARTIIND": "CHEMICALS",
    "AAVAS": "FINANCE",
    "ABB": "INFRA",
    "ABBOTINDIA": "HEALTHCARE",
    "ABCAPITAL": "FINANCE",
    "ABDL": "FMCG",
    "ABFRL": "CONSUMER",
    "ABLBL": "CONSUMER",
    "ABREL": "REALTY",
    "ABSLAMC": "FINANCE",
    "ACC": "CEMENT",
    "ACE": "INFRA",
    "ACMESOLAR": "ENERGY",
    "ACUTAAS": "HEALTHCARE",
    "ADANIENSOL": "ENERGY",
    "ADANIENT": "INFRA",
    "ADANIGREEN": "ENERGY",
    "ADANIPORTS": "INFRA",
    "ADANIPOWER": "ENERGY",
    "AEGISLOG": "ENERGY",
    "AEGISVOPAK": "ENERGY",
    "AFCONS": "INFRA",
    "AFFLE": "IT",
    "AIAENG": "INFRA",
    "AIIL": "FINANCE",
    "AJANTPHARM": "HEALTHCARE",
    "ALKEM": "HEALTHCARE",
    "AMBER": "CONSUMER",
    "AMBUJACEM": "CEMENT",
    "ANANDRATHI": "FINANCE",
    "ANANTRAJ": "REALTY",
    "ANGELONE": "FINANCE",
    "ANTHEM": "HEALTHCARE",
    "ANURAS": "CHEMICALS",
    "APARINDS": "INFRA",
    "APLAPOLLO": "METALS",
    "APOLLOHOSP": "HEALTHCARE",
    "APOLLOTYRE": "AUTO",
    "APTUS": "FINANCE",
    "ARE&M": "AUTO",
    "ASAHIINDIA": "AUTO",
    "ASHOKLEY": "INFRA",
    "ASIANPAINT": "CHEMICALS",
    "ASTERDM": "HEALTHCARE",
    "ASTRAL": "INFRA",
    "ATGL": "ENERGY",
    "ATHERENERG": "AUTO",
    "ATUL": "CHEMICALS",
    "AUBANK": "BANK",
    "AUROPHARMA": "HEALTHCARE",
    "AWL": "FMCG",
    "AXISBANK": "BANK",
    "BAJAJ-AUTO": "AUTO",
    "BAJAJFINSV": "FINANCE",
    "BAJAJHFL": "FINANCE",
    "BAJAJHLDNG": "FINANCE",
    "BAJFINANCE": "FINANCE",
    "BALKRISIND": "AUTO",
    "BALRAMCHIN": "FMCG",
    "BANDHANBNK": "FINANCE",
    "BANKBARODA": "BANK",
    "BANKINDIA": "FINANCE",
    "BATAINDIA": "CONSUMER",
    "BAYERCROP": "CHEMICALS",
    "BBTC": "FMCG",
    "BDL": "INFRA",
    "BEL": "INFRA",
    "BELRISE": "AUTO",
    "BEML": "INFRA",
    "BERGEPAINT": "CONSUMER",
    "BHARATFORG": "AUTO",
    "BHARTIARTL": "TELECOM",
    "BHARTIHEXA": "TELECOM",
    "BHEL": "INFRA",
    "BIKAJI": "FMCG",
    "BIOCON": "HEALTHCARE",
    "BLS": "CONSUMER",
    "BLUEDART": "SERVICES",
    "BLUEJET": "HEALTHCARE",
    "BLUESTARCO": "CONSUMER",
    "BOSCHLTD": "AUTO",
    "BPCL": "ENERGY",
    "BRIGADE": "REALTY",
    "BRITANNIA": "FMCG",
    "BSE": "FINANCE",
    "BSOFT": "IT",
    "CAMS": "FINANCE",
    "CANBK": "BANK",
    "CANFINHOME": "FINANCE",
    "CANHLIFE": "FINANCE",
    "CAPLIPOINT": "PHARMA",
    "CARBORUNIV": "INFRA",
    "CARTRADE": "CONSUMER",
    "CASTROLIND": "ENERGY",
    "CCL": "FMCG",
    "CDSL": "FINANCE",
    "CEATLTD": "AUTO",
    "CEMPRO": "INFRA",
    "CENTRALBK": "FINANCE",
    "CESC": "ENERGY",
    "CGCL": "FINANCE",
    "CGPOWER": "INFRA",
    "CHALET": "CONSUMER",
    "CHAMBLFERT": "CHEMICALS",
    "CHENNPETRO": "ENERGY",
    "CHOICEIN": "FINANCE",
    "CHOLAFIN": "FINANCE",
    "CHOLAHLDNG": "FINANCE",
    "CIEINDIA": "AUTO",
    "CIPLA": "PHARMA",
    "CLEAN": "CHEMICALS",
    "COALINDIA": "ENERGY",
    "COCHINSHIP": "INFRA",
    "COFORGE": "IT",
    "COHANCE": "HEALTHCARE",
    "COLPAL": "FMCG",
    "CONCOR": "SERVICES",
    "CONCORDBIO": "HEALTHCARE",
    "COROMANDEL": "CHEMICALS",
    "CPPLUS": "INFRA",
    "CRAFTSMAN": "AUTO",
    "CREDITACC": "FINANCE",
    "CRISIL": "FINANCE",
    "CROMPTON": "CONSUMER",
    "CUB": "FINANCE",
    "CUMMINSIND": "INFRA",
    "CYIENT": "IT",
    "DABUR": "FMCG",
    "DALBHARAT": "CEMENT",
    "DATAPATTNS": "INFRA",
    "DCMSHRIRAM": "OTHER",
    "DEEPAKFERT": "CHEMICALS",
    "DEEPAKNTR": "CHEMICALS",
    "DELHIVERY": "SERVICES",
    "DEVYANI": "CONSUMER",
    "DIVISLAB": "PHARMA",
    "DIXON": "CONSUMER",
    "DLF": "REALTY",
    "DMART": "CONSUMER",
    "DOMS": "FMCG",
    "DRREDDY": "PHARMA",
    "ECLERX": "SERVICES",
    "EICHERMOT": "AUTO",
    "EIDPARRY": "FMCG",
    "EIHOTEL": "CONSUMER",
    "ELECON": "INFRA",
    "ELGIEQUIP": "INFRA",
    "EMAMILTD": "FMCG",
    "EMCURE": "HEALTHCARE",
    "EMMVEE": "INFRA",
    "ENDURANCE": "AUTO",
    "ENGINERSIN": "INFRA",
    "ENRIN": "INFRA",
    "ERIS": "HEALTHCARE",
    "ESCORTS": "AUTO",
    "ETERNAL": "CONSUMER",
    "EXIDEIND": "AUTO",
    "FACT": "CHEMICALS",
    "FEDERALBNK": "BANK",
    "FINCABLES": "INFRA",
    "FIRSTCRY": "CONSUMER",
    "FIVESTAR": "FINANCE",
    "FLUOROCHEM": "CHEMICALS",
    "FORCEMOT": "AUTO",
    "FORTIS": "HEALTHCARE",
    "FSL": "SERVICES",
    "GABRIEL": "AUTO",
    "GAIL": "ENERGY",
    "GALLANTT": "INFRA",
    "GESHIP": "SERVICES",
    "GICRE": "FINANCE",
    "GILLETTE": "FMCG",
    "GLAND": "HEALTHCARE",
    "GLAXO": "HEALTHCARE",
    "GLENMARK": "HEALTHCARE",
    "GMDCLTD": "METALS",
    "GMRAIRPORT": "SERVICES",
    "GODFRYPHLP": "FMCG",
    "GODIGIT": "FINANCE",
    "GODREJCP": "FMCG",
    "GODREJIND": "OTHER",
    "GODREJPROP": "REALTY",
    "GPIL": "INFRA",
    "GRANULES": "HEALTHCARE",
    "GRAPHITE": "METALS",
    "GRASIM": "CEMENT",
    "GRAVITA": "METALS",
    "GROWW": "FINANCE",
    "GRSE": "INFRA",
    "GVT&D": "INFRA",
    "HAL": "INFRA",
    "HAVELLS": "CONSUMER",
    "HBLENGINE": "INFRA",
    "HCLTECH": "IT",
    "HDBFS": "FINANCE",
    "HDFCAMC": "FINANCE",
    "HDFCBANK": "BANK",
    "HDFCLIFE": "INSURANCE",
    "HEROMOTOCO": "AUTO",
    "HEXT": "IT",
    "HINDALCO": "METALS",
    "HINDCOPPER": "METALS",
    "HINDPETRO": "ENERGY",
    "HINDUNILVR": "FMCG",
    "HINDZINC": "METALS",
    "HOMEFIRST": "FINANCE",
    "HONASA": "FMCG",
    "HONAUT": "INFRA",
    "HSCL": "CHEMICALS",
    "HUDCO": "FINANCE",
    "HYUNDAI": "AUTO",
    "ICICIAMC": "FINANCE",
    "ICICIBANK": "BANK",
    "ICICIGI": "INSURANCE",
    "ICICIPRULI": "INSURANCE",
    "IDBI": "FINANCE",
    "IDEA": "TELECOM",
    "IDFCFIRSTB": "BANK",
    "IEX": "FINANCE",
    "IFCI": "FINANCE",
    "IGIL": "SERVICES",
    "IGL": "ENERGY",
    "IIFL": "FINANCE",
    "IKS": "IT",
    "INDGN": "HEALTHCARE",
    "INDHOTEL": "CONSUMER",
    "INDIACEM": "CEMENT",
    "INDIAMART": "CONSUMER",
    "INDIANB": "FINANCE",
    "INDIGO": "SERVICES",
    "INDUSINDBK": "BANK",
    "INDUSTOWER": "TELECOM",
    "INFY": "IT",
    "INOXWIND": "ENERGY",
    "INTELLECT": "IT",
    "IOB": "FINANCE",
    "IOC": "ENERGY",
    "IPCALAB": "HEALTHCARE",
    "IRB": "INFRA",
    "IRCON": "INFRA",
    "IRCTC": "CONSUMER",
    "IREDA": "FINANCE",
    "IRFC": "FINANCE",
    "ITC": "FMCG",
    "ITCHOTELS": "CONSUMER",
    "ITI": "TELECOM",
    "J&KBANK": "FINANCE",
    "JAINREC": "METALS",
    "JBMA": "AUTO",
    "JINDALSAW": "INFRA",
    "JINDALSTEL": "METALS",
    "JIOFIN": "FINANCE",
    "JKCEMENT": "CEMENT",
    "JKTYRE": "AUTO",
    "JMFINANCIL": "FINANCE",
    "JPPOWER": "ENERGY",
    "JSL": "METALS",
    "JSWCEMENT": "CEMENT",
    "JSWDULUX": "CONSUMER",
    "JSWENERGY": "ENERGY",
    "JSWINFRA": "SERVICES",
    "JSWSTEEL": "METALS",
    "JUBLFOOD": "CONSUMER",
    "JUBLINGREA": "CHEMICALS",
    "JUBLPHARMA": "HEALTHCARE",
    "JWL": "INFRA",
    "JYOTICNC": "INFRA",
    "KAJARIACER": "CONSUMER",
    "KALYANKJIL": "CONSUMER",
    "KARURVYSYA": "FINANCE",
    "KAYNES": "INFRA",
    "KEC": "INFRA",
    "KEI": "INFRA",
    "KFINTECH": "FINANCE",
    "KIMS": "HEALTHCARE",
    "KIRLOSENG": "INFRA",
    "KOTAKBANK": "BANK",
    "KPIL": "INFRA",
    "KPITTECH": "IT",
    "KPRMILL": "TEXTILES",
    "LALPATHLAB": "HEALTHCARE",
    "LATENTVIEW": "IT",
    "LAURUSLABS": "PHARMA",
    "LEMONTREE": "CONSUMER",
    "LENSKART": "CONSUMER",
    "LGEINDIA": "CONSUMER",
    "LICHSGFIN": "FINANCE",
    "LICI": "FINANCE",
    "LINDEINDIA": "CHEMICALS",
    "LLOYDSME": "METALS",
    "LODHA": "REALTY",
    "LT": "INFRA",
    "LTF": "FINANCE",
    "LTFOODS": "FMCG",
    "LTM": "IT",
    "LTTS": "IT",
    "LUPIN": "HEALTHCARE",
    "M&M": "AUTO",
    "M&MFIN": "FINANCE",
    "MAHABANK": "FINANCE",
    "MANAPPURAM": "FINANCE",
    "MANKIND": "PHARMA",
    "MAPMYINDIA": "IT",
    "MARICO": "FMCG",
    "MARUTI": "AUTO",
    "MAXHEALTH": "HEALTHCARE",
    "MAZDOCK": "INFRA",
    "MCX": "FINANCE",
    "MEDANTA": "HEALTHCARE",
    "MEESHO": "CONSUMER",
    "MFSL": "INSURANCE",
    "MGL": "ENERGY",
    "MINDACORP": "AUTO",
    "MMTC": "SERVICES",
    "MOTHERSON": "AUTO",
    "MOTILALOFS": "FINANCE",
    "MPHASIS": "IT",
    "MRF": "AUTO",
    "MRPL": "ENERGY",
    "MSUMI": "AUTO",
    "MUTHOOTFIN": "FINANCE",
    "NAM-INDIA": "FINANCE",
    "NATCOPHARM": "HEALTHCARE",
    "NATIONALUM": "METALS",
    "NAUKRI": "CONSUMER",
    "NAVA": "ENERGY",
    "NAVINFLUOR": "CHEMICALS",
    "NBCC": "INFRA",
    "NCC": "INFRA",
    "NESTLEIND": "FMCG",
    "NETWEB": "IT",
    "NEULANDLAB": "HEALTHCARE",
    "NEWGEN": "IT",
    "NH": "HEALTHCARE",
    "NHPC": "ENERGY",
    "NIACL": "FINANCE",
    "NIVABUPA": "FINANCE",
    "NLCINDIA": "ENERGY",
    "NMDC": "METALS",
    "NSLNISP": "METALS",
    "NTPC": "ENERGY",
    "NTPCGREEN": "ENERGY",
    "NUVAMA": "FINANCE",
    "NUVOCO": "CEMENT",
    "NYKAA": "CONSUMER",
    "OBEROIRLTY": "REALTY",
    "OFSS": "IT",
    "OIL": "ENERGY",
    "OLAELEC": "AUTO",
    "OLECTRA": "AUTO",
    "ONESOURCE": "HEALTHCARE",
    "ONGC": "ENERGY",
    "PAGEIND": "TEXTILES",
    "PARADEEP": "CHEMICALS",
    "PATANJALI": "FMCG",
    "PAYTM": "FINANCE",
    "PCBL": "CHEMICALS",
    "PERSISTENT": "IT",
    "PETRONET": "ENERGY",
    "PFC": "FINANCE",
    "PFIZER": "HEALTHCARE",
    "PFOCUS": "MEDIA",
    "PGEL": "CONSUMER",
    "PHOENIXLTD": "REALTY",
    "PIDILITIND": "CHEMICALS",
    "PIIND": "CHEMICALS",
    "PINELABS": "FINANCE",
    "PIRAMALFIN": "FINANCE",
    "PNB": "FINANCE",
    "PNBHOUSING": "FINANCE",
    "POLICYBZR": "FINANCE",
    "POLYCAB": "INFRA",
    "POLYMED": "HEALTHCARE",
    "POONAWALLA": "FINANCE",
    "POWERGRID": "ENERGY",
    "POWERINDIA": "INFRA",
    "PPLPHARMA": "HEALTHCARE",
    "PREMIERENE": "INFRA",
    "PRESTIGE": "REALTY",
    "PTCIL": "INFRA",
    "PVRINOX": "MEDIA",
    "PWL": "CONSUMER",
    "RADICO": "FMCG",
    "RAILTEL": "TELECOM",
    "RAINBOW": "HEALTHCARE",
    "RAMCOCEM": "CEMENT",
    "RBLBANK": "BANK",
    "RECLTD": "FINANCE",
    "REDINGTON": "SERVICES",
    "RELIANCE": "ENERGY",
    "RHIM": "INFRA",
    "RITES": "INFRA",
    "RKFORGE": "AUTO",
    "RPOWER": "ENERGY",
    "RRKABEL": "INFRA",
    "RVNL": "INFRA",
    "SAGILITY": "IT",
    "SAIL": "METALS",
    "SAILIFE": "HEALTHCARE",
    "SAMMAANCAP": "FINANCE",
    "SAPPHIRE": "CONSUMER",
    "SARDAEN": "METALS",
    "SAREGAMA": "MEDIA",
    "SBFC": "FINANCE",
    "SBICARD": "FINANCE",
    "SBILIFE": "INSURANCE",
    "SBIN": "BANK",
    "SCHAEFFLER": "AUTO",
    "SCHNEIDER": "INFRA",
    "SCI": "SERVICES",
    "SHREECEM": "CEMENT",
    "SHRIRAMFIN": "FINANCE",
    "SHYAMMETL": "INFRA",
    "SIEMENS": "INFRA",
    "SIGNATURE": "REALTY",
    "SJVN": "ENERGY",
    "SOBHA": "REALTY",
    "SOLARINDS": "CHEMICALS",
    "SONACOMS": "AUTO",
    "SONATSOFTW": "IT",
    "SPLPETRO": "CHEMICALS",
    "SRF": "CHEMICALS",
    "STARHEALTH": "FINANCE",
    "SUMICHEM": "CHEMICALS",
    "SUNDARMFIN": "FINANCE",
    "SUNPHARMA": "PHARMA",
    "SUNTV": "MEDIA",
    "SUPREMEIND": "INFRA",
    "SUZLON": "INFRA",
    "SWANCORP": "CHEMICALS",
    "SWIGGY": "CONSUMER",
    "SYNGENE": "HEALTHCARE",
    "SYRMA": "INFRA",
    "TARIL": "INFRA",
    "TATACAP": "FINANCE",
    "TATACHEM": "CHEMICALS",
    "TATACOMM": "TELECOM",
    "TATACONSUM": "FMCG",
    "TATAELXSI": "IT",
    "TATAINVEST": "FINANCE",
    "TATAPOWER": "ENERGY",
    "TATASTEEL": "METALS",
    "TATATECH": "IT",
    "TBOTEK": "CONSUMER",
    "TCS": "IT",
    "TECHM": "IT",
    "TECHNOE": "INFRA",
    "TEGA": "INFRA",
    "TEJASNET": "TELECOM",
    "TENNIND": "AUTO",
    "THELEELA": "CONSUMER",
    "THERMAX": "INFRA",
    "TIINDIA": "AUTO",
    "TIMKEN": "INFRA",
    "TITAGARH": "INFRA",
    "TITAN": "CONSUMER",
    "TMCV": "INFRA",
    "TMPV": "AUTO",
    "TORNTPHARM": "PHARMA",
    "TORNTPOWER": "ENERGY",
    "TRAVELFOOD": "CONSUMER",
    "TRENT": "CONSUMER",
    "TRIDENT": "TEXTILES",
    "TRITURBINE": "INFRA",
    "TTML": "TELECOM",
    "TVSMOTOR": "AUTO",
    "UBL": "FMCG",
    "UCOBANK": "FINANCE",
    "ULTRACEMCO": "CEMENT",
    "UNIONBANK": "BANK",
    "UNITDSPR": "CONSUMER",
    "UNOMINDA": "AUTO",
    "UPL": "CHEMICALS",
    "URBANCO": "CONSUMER",
    "USHAMART": "INFRA",
    "UTIAMC": "FINANCE",
    "VBL": "FMCG",
    "VEDL": "METALS",
    "VIJAYA": "HEALTHCARE",
    "VMM": "CONSUMER",
    "VOLTAS": "CONSUMER",
    "VTL": "TEXTILES",
    "WAAREEENER": "INFRA",
    "WELCORP": "INFRA",
    "WELSPUNLIV": "TEXTILES",
    "WHIRLPOOL": "CONSUMER",
    "WIPRO": "IT",
    "WOCKPHARMA": "HEALTHCARE",
    "YESBANK": "FINANCE",
    "ZEEL": "MEDIA",
    "ZENSARTECH": "IT",
    "ZENTEC": "INFRA",
    "ZFCVINDIA": "AUTO",
    "ZYDUSLIFE": "PHARMA",
    "ZYDUSWELL": "FMCG",
}
